export const ERROR_CODES = {
  BAD_REQUEST: "BAD_REQUEST",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  TOKEN_INVALID: "TOKEN_INVALID",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
  INSUFFICIENT_ROLE: "INSUFFICIENT_ROLE",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  FIREBASE_NOT_CONFIGURED: "FIREBASE_NOT_CONFIGURED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
