"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const adminController_1 = require("../controllers/adminController");
const authenticate_1 = require("../middleware/authenticate");
const authorize_1 = require("../middleware/authorize");
const asyncHandler_1 = require("../utils/asyncHandler");
const router = (0, express_1.Router)();
router.post("/claims", authenticate_1.authenticate, (0, authorize_1.authorize)({ allowedRoles: ["admin"] }), (0, asyncHandler_1.asyncHandler)(adminController_1.setUserRole));
exports.default = router;
